from docx import Document
from docx.shared import Pt
from docx.enum.text import WD_ALIGN_PARAGRAPH

doc = Document()
styles = doc.styles
styles["Normal"].font.name = "Calibri"
styles["Normal"].font.size = Pt(11)

title = doc.add_heading("Artificial Intelligence & Machine Learning – Beginner Notes", 0)
title.alignment = WD_ALIGN_PARAGRAPH.CENTER

sections = [
("1. Basics of Artificial Intelligence and Machine Learning", [
("What is Artificial Intelligence (AI)?",
"Artificial Intelligence (AI) is technology that enables computers or machines to perform tasks that normally require human intelligence.\n\nSimple meaning: AI = Making machines behave intelligently.\n\nExamples: ChatGPT, Google Maps, face unlock, voice assistants, recommendation systems, and self-driving technology."),
("What is Machine Learning (ML)?",
"Machine Learning is a branch of AI where computers learn patterns from data and use those patterns to make predictions or decisions.\n\nTraditional programming: Data + Rules → Output\nMachine Learning: Data + Examples → Learn Pattern → Prediction."),
("Basic Machine Learning Process",
"Collect Data → Clean Data → Prepare Data → Train ML Model → Test Model → Evaluate Model → Make Predictions"),
("Important Terms",
"Data: Information used by the system.\nFeature: Input information used for prediction.\nTarget: The value we want to predict.\nModel: A system that learns patterns from data.\nTraining: Teaching the model using existing data.\nTesting: Checking the model on unseen data.\nPrediction: Output generated by the trained model.")
]),
("2. Difference Between AI, ML, and Deep Learning", [
("Relationship","Artificial Intelligence (AI) → Machine Learning (ML) → Deep Learning (DL)\n\nDeep Learning is a part of Machine Learning, and Machine Learning is a part of AI."),
("AI","The broadest concept. It focuses on making machines perform intelligent tasks."),
("ML","A subset of AI where systems learn patterns from data."),
("Deep Learning","A subset of ML that uses artificial neural networks with multiple layers to learn complex patterns."),
("Quick Comparison","AI = Intelligence\nML = Learning from Data\nDL = Learning with Deep Neural Networks")
]),
("3. Real-World Applications of AI", [
("Healthcare","Medical image analysis, disease-risk prediction, patient monitoring, and drug discovery."),
("Banking and Finance","Fraud detection, credit scoring, risk analysis, customer churn prediction, and transaction monitoring."),
("E-Commerce","Product recommendations, search, customer behavior analysis, demand forecasting, and chatbots."),
("Transportation","Route optimization, traffic prediction, driver assistance, and autonomous driving research."),
("Entertainment","Movie, music, video, and show recommendations."),
("Chatbots and Generative AI","Question answering, text generation, summarization, translation, code generation, and image generation."),
("Cybersecurity","Detecting suspicious activity, malware, unusual network behavior, and potential attacks.")
]),
("4. Install Python and Practice Programming Concepts", [
("What is Python?","Python is a high-level, general-purpose programming language. It is widely used in AI, ML, Data Science, Web Development, Automation, and Software Development."),
("Installation","Install Python from the official Python website: https://www.python.org/\nCheck installation in Command Prompt with: python --version or py --version"),
("Variables","Variables store values.\nExample: name = \"Lokesh\"; age = 21; marks = 85.5"),
("Common Data Types","int → 10\nfloat → 10.5\nstr → \"Hello\"\nbool → True / False\nlist → [10, 20, 30]"),
("Input","input() takes user input. Example: name = input(\"Enter your name: \")"),
("Operators","+ Addition, - Subtraction, * Multiplication, / Division, % Remainder, ** Power"),
("Conditional Statements","if, elif, and else are used to make decisions."),
("Loops","for and while loops repeat a task."),
("Lists","Lists store multiple values. Example: numbers = [10, 20, 30, 40]. Python indexing starts from 0."),
("Functions","A function is a reusable block of code that performs a specific task.\nExample:\ndef greet(name):\n    print(\"Hello\", name)")
]),
("5. Beginner-Friendly Python Programs", [
("Program 1: Hello World",'print("Hello World")'),
("Program 2: Add Two Numbers",'a = 10\nb = 20\nsum = a + b\nprint("Sum:", sum)'),
("Program 3: Check Even or Odd",'number = int(input("Enter a number: "))\n\nif number % 2 == 0:\n    print("Even")\nelse:\n    print("Odd")'),
("Program 4: Largest of Two Numbers",'a = int(input("Enter first number: "))\nb = int(input("Enter second number: "))\n\nif a > b:\n    print("Largest:", a)\nelse:\n    print("Largest:", b)'),
("Program 5: Print Numbers 1 to 10",'for i in range(1, 11):\n    print(i)'),
("Program 6: Sum of 1 to 10",'total = 0\n\nfor i in range(1, 11):\n    total = total + i\n\nprint("Total:", total)'),
("Program 7: Largest Number in a List",'numbers = [10, 25, 5, 40, 15]\n\nlargest = numbers[0]\n\nfor number in numbers:\n    if number > largest:\n        largest = number\n\nprint("Largest:", largest)'),
("Program 8: Count Even Numbers",'numbers = [1, 2, 3, 4, 5, 6]\n\ncount = 0\n\nfor number in numbers:\n    if number % 2 == 0:\n        count = count + 1\n\nprint("Even numbers:", count)')
]),
("Quick Revision Sheet", [
("Key Concepts","AI: Machines performing intelligent tasks\nML: Machines learning patterns from data\nDeep Learning: ML using deep neural networks\nVariable: Stores a value\nData Type: Type of stored value\nif: Makes a decision\nfor: Repeats code\nwhile: Repeats while a condition is true\nList: Stores multiple values\nFunction: Reusable block of code\ninput(): Takes user input\nprint(): Displays output"),
("Big Picture","Artificial Intelligence → Machine Learning → Deep Learning → Python → Data → Algorithms → Train Model → Test Model → Evaluate Model → Prediction"),
("Beginner Rule","For every program, ask: 1. What is the input? 2. What processing is needed? 3. What condition/loop is required? 4. What should be the output?")
])
]

for heading, items in sections:
    doc.add_heading(heading, level=1)
    for sub, text in items:
        doc.add_heading(sub, level=2)
        p = doc.add_paragraph()
        p.add_run(text)

path = "/mnt/data/AI_ML_Beginner_Notes.docx"
doc.save(path)
print(path)
